### ISSUE TITLE
The link on crates.io is broken

### ISSUE THREAD

**Issue by BentEngbers** [leotaku/tower-livereload#14]
The link goes to <https://github.com/leotaku/tower-livereload/examples/livehttpd> but this does not seem to exist.
perhaps is should be <https://github.com/leotaku/tower-livereload/tree/master/examples/livehttpd>?

![image](https://github.com/leotaku/tower-livereload/assets/16548374/b25aaffa-1fa8-4d51-85b8-a6e2c29d33b5)

**Comment by leotaku** [comment]
Thank you! I will have this fixed in the next release!

**Comment by leotaku** [comment]
I've just made a new release, so the link is now fixed on crates.io. As such, I am closing this issue.
