### ISSUE TITLE
[bug] `tower-livereload` doesn't work with latest version of axum

### ISSUE THREAD

**Issue by ankush** [leotaku/tower-livereload#19]
To reproduce: run axum example on latest version of axum - https://github.com/leotaku/tower-livereload/tree/master/examples/axum-dev-only

My hunch is this change https://github.com/tokio-rs/axum/pull/3031 defers setting content-length, one of the heuristics used for injecting.

**Comment by leotaku** [comment]
Good catch, thank you. I suppose we will have to just remove that heuristic.

**Comment by leotaku** [comment]
Should be fixed by #20. Feel free to reopen if you still experience the issue.
